"""Team 5: レポート統括チーム（日次統合レポート生成）

run_teams.py から抽出。
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

from teams._base import (
    call_claude, call_gemini, save_source_log,
    load_json, _fetch_fresh_price,
    read_report, is_generated, screen_to_list, _score_num, _rs26w, write_report,
    save_kpi_log, build_kpi_check_prompt,
    read_shared_context, update_shared_context, get_feedback_prefix,
    read_knowledge, write_knowledge,
    LABEL_RULE, SHARED_CTX_PATH, KNOWLEDGE_DIR,
)
from teams._config import TEAM_KPIS, SOURCE_RELIABILITY
from teams._context import (
    TODAY, WEEKDAY, IS_MARKET_DAY,
    DAY_MODE, DAY_LABEL, DAY_FOCUS,
    DATA_DIR, REPORT_DIR,
    client, MODEL, GEMINI_KEY, GEMINI_URL,
)
from teams._tools import _run_agent_team
from teams._phase import detect_phase
from teams._scenarios import (
    MAX_SIM_SLOTS,
    _make_new_sim, _get_week_target, _determine_leading_scenario,
    _scenario_gaps, _generate_scenarios, _analyze_daily_deviation,
    _get_sector_group, _check_sector_diversity, _weekly_scenario_review,
)


# ─── Team 5: レポート統括 ─────────────────────────────────────────
def run_daily_report():
    print(f'  [エージェント起動] レポート統括 ({DAY_LABEL})')

    system = _agent_system_prompt(
        'レポート統括',
        '全チームの情報を統合し、投資家が即座に行動できる統合デイリーレポートを作成する。'
        '各チームレポートの要点を抽出し、矛盾がないか確認する。'
        '全チーム統合率100%・翌日注目点3件以上・[事実]/[AI分析]ラベル遵守が必須KPI。'
    )

    # 未生成チームを事前確認
    info = read_report('info_gathering')
    analysis = read_report('analysis')
    risk = read_report('risk')
    strategy = read_report('strategy')
    missing_teams = [name for name, content in [
        ('情報収集チーム', info), ('銘柄選定・仮説チーム', analysis),
        ('リスク管理チーム', risk), ('投資戦略チーム', strategy)
    ] if not is_generated(content)]
    missing_notice = f"⚠️ 未生成チーム: {', '.join(missing_teams)}" if missing_teams else "全チームレポート生成済み"

    initial = f"""本日{TODAY}（{DAY_LABEL}）の統合デイリーレポートを作成してください。

【状況】{missing_notice}

【手順】
1. read_knowledge("report_patterns") で過去の統合パターン・品質改善点を確認
2. 各チームレポートをread_past_reportで読む（既に読み込み済みだが追加詳細は参照可）
3. search_market_info で翌日・来週の追加注目情報を収集:
   - "{TODAY} 明日 決算発表 経済指標 スケジュール"
4. write_knowledge("report_patterns") で今日の統合で気づいた改善点を保存
5. finalize_report で統合レポートを完成させる（これがlatest_reportにも保存される）

【各チームレポートサマリー（既取得）】
■ 情報収集: {info[:600] if is_generated(info) else '（未生成）'}
■ 銘柄選定: {analysis[:800] if is_generated(analysis) else '（未生成）'}
■ リスク管理: {risk[:500] if is_generated(risk) else '（未生成）'}
■ 投資戦略: {strategy[:800] if is_generated(strategy) else '（未生成）'}

【レポートフォーマット】
# 📊 デイリー投資レポート {TODAY}

## エグゼクティブサマリー
（3〜5行で要点・市場環境判定・最重要アクション）

## 市場環境: [Attack/Steady/Defend]

## 本日のアクションプラン（優先順）
1. **[最優先]** ...

## 注目銘柄サマリー
| ランク | 銘柄 | コード | ポイント |

## リスク警戒事項

## 翌日以降の注目スケジュール

## 各チーム詳細（200字以内で各チームを要約）

---
Generated by Investment Team Agent System (Claude + Gemini)"""

    # エージェントが finalize_report を呼ぶと content が返る
    result = _run_agent_team('report', 'レポート統括', system, initial, f'{TODAY}_daily_report')
    if result:
        write_report('latest_report', result)


# ─── フェーズ自動判定（ルールベース） ────────────────────────────────
from teams._phase import detect_phase


